name: pr-ci-pipeline

on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - staging
  pull_request:
    branches:
      - main
      - develop
      - feature/*
      - staging

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Install Gradle
        run: |
          sudo apt update
          sudo apt install -y gradle

      - name: Run Checkstyle
        run: |
          ./gradlew checkstyleMain checkstyleTest --continue

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Install Gradle
        run: |
          sudo apt update
          sudo apt install -y gradle

      - name: Run Tests
        run: |
          ./gradlew test --continue

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Install Gradle
        run: |
          sudo apt update
          sudo apt install -y gradle

      - name: Build Project
        run: |
          ./gradlew build --continue
